# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,TCP
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: TCP-plugin
  prometheus:
    metrics:
      export:
        enabled: true