# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mqtt-v2
  endpoint:
    health:
      show-details: when-Authorized
    mqtt-v2:
      enabled: true

# Spring Boot Actuator 自定义端点
info:
  app:
    name: CN-Universal MQTT-v2
    description: MQTT-v2 消息处理模块
    version: 2.0.0
    Author: Aleo
    contact: wo8335224@gmail.com

# 主题前缀配置
topic:
  thing-prefix: "${mqtt.v2.topic.thing-prefix:$thing}"
  ota-prefix: "${mqtt.v2.topic.ota-prefix:$ota}"

# 主题配置（JSON格式）
topic-config: |
  {
    "thing-model": {
      "description": "物模型主题",
      "topics": [
        "${mqtt.v2.topic.thing-prefix:$thing}/up/property/+/+",
        "${mqtt.v2.topic.thing-prefix:$thing}/up/event/+/+", 
        "${mqtt.v2.topic.thing-prefix:$thing}/down/+/+"
      ]
    },
    "system-level": {
      "description": "系统级主题",
      "topics": [
        "${mqtt.v2.topic.ota-prefix:$ota}/report/+/+",
        "${mqtt.v2.topic.ota-prefix:$ota}/update/+/+"
      ]
    },
    "passthrough": {
      "description": "透传主题",
      "topics": [
        "${mqtt.v2.topic.thing-prefix:$thing}/up/+/+",
        "${mqtt.v2.topic.thing-prefix:$thing}/down/+/+"
      ]
    }
  }

# 统计信息日志打印配置
statistics:
  logging:
    enabled: true                    # 是否启用统计信息日志打印
    interval: 300                    # 打印间隔（秒），默认5分钟
    detailed: false                  # 是否打印详细统计信息 